services:
  gobang-app:
    container_name: gobang-app
    build:
      context: .
      dockerfile: docker/gobang-app/Dockerfile
    networks:
      - gobang-network
    ports:
      - ${APPPORT:-3000}:3000
    depends_on:
      - gobang-auth

  gobang-auth:
    container_name: gobang-auth
    build:
      context: .
      dockerfile: docker/gobang-auth/Dockerfile
    networks:
      - gobang-network
    ports:
      - "${AUTHPORT:-8080}:${AUTHPORT:-8080}"
    depends_on:
      - gobang-db
  gobang-db:
    container_name: gobang-db
    image: mysql:latest
    networks:
      - gobang-network
    volumes:
      - gobang-db:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
      - MYSQL_DATABASE=${DB_NAME:-gobang}

volumes:
  gobang-db:
    name: gobang-db
    driver: local

networks:
  gobang-network:
    name: gobang-network
    driver: bridge
