services:
  gobang:
    container_name: gobang_app
    build: .
    networks:
      - gobang_network
    ports:
      - ${PORT:-8080}:8080
    environment:
      - PORT=${PORT:-8080}
      - DB_PORT=${DB_PORT:-3306}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME:-gobang}
    depends_on:
      - db

  db:
    container_name: gobang_db
    image: mysql:latest
    networks:
      - gobang_network
    ports:
      - ${DB_PORT:-3306}:3306
    environment:
      - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
      - MYSQL_DATABASE=${DB_NAME:-gobang}

volumes:
  gobang_db:
    name: gobang_db
    driver: local

networks:
  gobang:
    name: gobang_network
    driver: bridge
