services:
  gobang_app:
    container_name: gobang_app
    build:
      context: .
      dockerfile: docker/gobangApp/Dockerfile
    networks:
      - gobang
    ports:
      - ${APPPORT:-3000}:3000
    depends_on:
      - gobang_auth

  gobang_auth:
    container_name: gobang_auth
    build:
      context: .
      dockerfile: docker/gobangAuth/Dockerfile
    networks:
      - gobang
    ports:
      - "${PORT:-8080}:8080"
    depends_on:
      - gobang_db
  gobang_db:
    container_name: gobang_db
    image: mysql:latest
    networks:
      - gobang
    environment:
      - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
      - MYSQL_DATABASE=${DB_NAME:-gobang}

volumes:
  gobang_db:
    name: gobang_db
    driver: local

networks:
  gobang:
    name: gobang_network
    driver: bridge
